server:
  port : 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true

spring:
  application:
    name: shoppingmall
  datasource:
    username: 'user'
    password: '1234'
    url: jdbc:h2:tcp://localhost/~/shoppingmall
    driver-class-name: org.h2.Driver
    initialization-mode: always
  h2:
    console:
      enabled: true
    datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/shoppingmall;MODE=MYSQL
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: 'none'
    show-sql : true
    properties:
      hibernate:
        dialect : org.hibernate.dialect.H2Dialect
        format_sql: true